### ISSUE TITLE
Bug: Editor UI is fullscreen

### ISSUE THREAD

**Issue by thismusicdude** [ThePat02/force-directed-graph-godot#11]
Sadly the Component Selection in the Editor is completly fullscreen which makes it rly hard to edit other components.
![image](https://github.com/user-attachments/assets/789f35bf-c353-4891-856d-bcf719bdce08)

**Comment by ThePat02** [comment]
Hey! I think you can just drag the component tray from the right to the left to resize it! This happens because I have not set a max-size.

**Comment by ThePat02** [comment]
Related issue #9

**Comment by thismusicdude** [comment]
hey thank you so much for your help! gonna try this :) 
Thank you for your work btw

**Comment by ThePat02** [comment]
> hey thank you so much for your help! gonna try this :)
Thank you for your work btw

Let me know if this works for you! If not I will reopen this and investigate further! Glad to see people are using my tools ^^
