### ISSUE TITLE
Selecting any ForceDirectedGraph Node in a scene covers entire 2D view

### ISSUE THREAD

**Issue by Goldenlion5648** [ThePat02/force-directed-graph-godot#9]
The editor view is completely covered when any nodes added by the addon are selected:

![image](https://github.com/ThePat02/force-directed-graph-godot/assets/32916571/db16b13d-fb4e-455c-98cc-5f0666bb5ed5)

but when selecting one of the labels:
![image](https://github.com/ThePat02/force-directed-graph-godot/assets/32916571/077e3f15-ae4c-4adb-a6cc-64f91dc13449)

If the addon is instead added in its own folder (not the addons folder), this is not an issue (though the node icons added by force-directed-graph don't show on the left)
![image](https://github.com/ThePat02/force-directed-graph-godot/assets/32916571/277ba2d9-d85e-495e-847b-fda5dd0428eb)

**Comment by Goldenlion5648** [comment]
Nevermind, the FDG menu just took up the whole window somehow 
![image](https://github.com/ThePat02/force-directed-graph-godot/assets/32916571/782922f5-8aa1-442c-a446-e59ecdeaec02)

**Comment by hero-clashes** [comment]
I got the same issue, isn't there a way to request a size?

**Comment by ThePat02** [comment]
Just found the problem: The `Expand` flag was set on the UI scene. This should prevent the UI from covering the whole screen when first opened.

@hero-clashes You can just manually drag the dock to fit your preferences.

As far as I know, there is no way to set a something like a maximum size on a `Control` node, but this should fix the problem for now!
